// <auto-generated />
using System;
using Alumni.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Alumni.Data.Migrations
{
    [DbContext(typeof(AlumniDbContext))]
    [Migration("20240702020408_Test")]
    partial class Test
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Alumni.Data.Models.CharityDonation", b =>
                {
                    b.Property<Guid>("CharityDonationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CurrentlyRaisedDonations")
                        .HasColumnType("decimal(12,3)");

                    b.Property<decimal>("DonationGoal")
                        .HasColumnType("decimal(12,3)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastEdited")
                        .HasColumnType("datetime2");

                    b.HasKey("CharityDonationId");

                    b.ToTable("CharityDonations");
                });

            modelBuilder.Entity("Alumni.Data.Models.CharityDonationUser", b =>
                {
                    b.Property<Guid>("CharityDonationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CharityDonationId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("CharityDonationsUsers");
                });

            modelBuilder.Entity("Alumni.Data.Models.Comment", b =>
                {
                    b.Property<Guid>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Contents")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastEdited")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("NewsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CommentId");

                    b.HasIndex("NewsId");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Alumni.Data.Models.Event", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Contents")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastEdited")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EventId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            EventId = new Guid("87c281f4-5052-47a5-a6f4-75c9741663ef"),
                            Contents = "The class of 2016 is going to have a meeting at the local park. There`s going to be food, but you can bring some.",
                            CreatedOn = new DateTime(2024, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDateTime = new DateTime(2024, 5, 2, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastEdited = new DateTime(2024, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDateTime = new DateTime(2024, 5, 2, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Meeting - 2016 class"
                        },
                        new
                        {
                            EventId = new Guid("541e7f5d-4016-474e-acd2-2f30ecd9a446"),
                            Contents = "The class of 2011 is going to have a meeting at the local beach.",
                            CreatedOn = new DateTime(2024, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDateTime = new DateTime(2024, 7, 5, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastEdited = new DateTime(2024, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDateTime = new DateTime(2024, 7, 5, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Meeting - 2011 class"
                        },
                        new
                        {
                            EventId = new Guid("9a1172e2-e2e5-44fd-92e6-285c1154e8dc"),
                            Contents = "The class of 2009 is going to have a meeting at the local pub.",
                            CreatedOn = new DateTime(2024, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDateTime = new DateTime(2024, 5, 8, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastEdited = new DateTime(2024, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDateTime = new DateTime(2024, 5, 8, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Meeting - 2009 class"
                        },
                        new
                        {
                            EventId = new Guid("832388e9-e1d9-4878-9299-273129c9f247"),
                            Contents = "The class of 2003 is going to have a meeting at the local pub.",
                            CreatedOn = new DateTime(2024, 7, 2, 5, 4, 7, 294, DateTimeKind.Local).AddTicks(1462),
                            EndDateTime = new DateTime(2024, 5, 8, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = true,
                            LastEdited = new DateTime(2024, 7, 2, 5, 4, 7, 294, DateTimeKind.Local).AddTicks(1464),
                            StartDateTime = new DateTime(2024, 5, 8, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Meeting - 2003 class"
                        },
                        new
                        {
                            EventId = new Guid("74a8ad71-9425-4115-8b44-55cc94b13a89"),
                            Contents = "The class of 2009 is going to have a meeting at the local pub.",
                            CreatedOn = new DateTime(2024, 7, 2, 5, 4, 7, 294, DateTimeKind.Local).AddTicks(1467),
                            EndDateTime = new DateTime(2024, 5, 8, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastEdited = new DateTime(2024, 7, 2, 5, 4, 7, 294, DateTimeKind.Local).AddTicks(1469),
                            StartDateTime = new DateTime(2010, 5, 8, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Meeting - 2009 class"
                        },
                        new
                        {
                            EventId = new Guid("8f0a57e7-afe3-4648-8efa-9a977602bee0"),
                            Contents = "The class of 2009 is going to have a meeting at the local pub.",
                            CreatedOn = new DateTime(2025, 5, 8, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            EndDateTime = new DateTime(2024, 5, 8, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastEdited = new DateTime(2024, 7, 2, 5, 4, 7, 294, DateTimeKind.Local).AddTicks(1473),
                            StartDateTime = new DateTime(2024, 5, 8, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Meeting - 2009 class"
                        },
                        new
                        {
                            EventId = new Guid("257cb7ad-df19-4cac-a009-f68eeb305afa"),
                            Contents = "The class of 2009 is going to have a meeting at the local pub.",
                            CreatedOn = new DateTime(2023, 5, 8, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            EndDateTime = new DateTime(2024, 5, 8, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastEdited = new DateTime(2022, 5, 8, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            StartDateTime = new DateTime(2024, 5, 8, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Meeting - 2009 class"
                        });
                });

            modelBuilder.Entity("Alumni.Data.Models.News", b =>
                {
                    b.Property<Guid>("NewsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Contents")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastEdited")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NewsId");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            NewsId = new Guid("85183070-d0af-41a1-9b3b-95d0073995eb"),
                            Contents = "Test seed",
                            CreatedOn = new DateTime(2024, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastEdited = new DateTime(2024, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "News"
                        },
                        new
                        {
                            NewsId = new Guid("fb8f1f7a-8853-4bed-8008-a17ae2a3be3f"),
                            Contents = "funny haha get shmucked",
                            CreatedOn = new DateTime(2024, 6, 1, 5, 4, 7, 294, DateTimeKind.Local).AddTicks(1116),
                            IsDeleted = true,
                            LastEdited = new DateTime(2024, 9, 15, 5, 4, 7, 294, DateTimeKind.Local).AddTicks(1119),
                            Title = "file"
                        },
                        new
                        {
                            NewsId = new Guid("31dedd8d-0dc7-455a-955a-14d7d5e9320f"),
                            Contents = "f k y u d b j g d",
                            CreatedOn = new DateTime(2024, 7, 2, 5, 4, 7, 294, DateTimeKind.Local).AddTicks(1123),
                            IsDeleted = false,
                            LastEdited = new DateTime(2024, 7, 2, 5, 4, 7, 294, DateTimeKind.Local).AddTicks(1124),
                            Title = "News"
                        });
                });

            modelBuilder.Entity("Alumni.Data.Models.Post", b =>
                {
                    b.Property<Guid>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Contents")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastEdited")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = new Guid("ecfccb98-75a2-49ee-910d-e5a5ec44ae5b"),
                            Contents = "On the 23.08.24 the alumni of Softuni Buditel will gather for a tea party in South park",
                            CreatedOn = new DateTime(2024, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastEdited = new DateTime(2024, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Alumni gathering",
                            UserId = new Guid("7388ce0f-df30-4686-9e49-46daac4e0292")
                        },
                        new
                        {
                            PostId = new Guid("7463e718-280e-47b6-93b3-f6d629e26a9d"),
                            Contents = "My master is a guy who likes to wear black and fights crime",
                            CreatedOn = new DateTime(2024, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastEdited = new DateTime(2024, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Just a random post",
                            UserId = new Guid("30913bf8-4000-4809-801e-764de3136c0e")
                        },
                        new
                        {
                            PostId = new Guid("ee03701f-f3c6-4872-8dc8-800a99947a9d"),
                            Contents = "I am prince Ferdinand, the first tzar of the new Bulgaria",
                            CreatedOn = new DateTime(2024, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = true,
                            LastEdited = new DateTime(2024, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Listen to your tzar",
                            UserId = new Guid("8d7ed0e0-1804-4283-aa5b-802033b2c918")
                        },
                        new
                        {
                            PostId = new Guid("2fae760d-6a45-45ed-ae78-e4451ebf47f8"),
                            Contents = "Hello everyone! I hope this message finds you well. I’m excited to announce the launch of our new alumni mentorship program, designed to connect recent graduates with experienced professionals. It's a great way to share your expertise, give back to our community, and help guide the next generation. Looking forward to seeing many of you get involved!",
                            CreatedOn = new DateTime(2024, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastEdited = new DateTime(2024, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Test",
                            UserId = new Guid("7388ce0f-df30-4686-9e49-46daac4e0292")
                        },
                        new
                        {
                            PostId = new Guid("22a984ee-76a2-4c73-b0bf-7ac5e30ccc1b"),
                            Contents = "Hello everyone! I hope this message finds you well. I’m excited to announce the launch of our new alumni mentorship program, designed to connect recent graduates with experienced professionals. It's a great way to share your expertise, give back to our community, and help guide the next generation. Looking forward to seeing many of you get involved!",
                            CreatedOn = new DateTime(2024, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastEdited = new DateTime(2024, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Test",
                            UserId = new Guid("7388ce0f-df30-4686-9e49-46daac4e0292")
                        },
                        new
                        {
                            PostId = new Guid("62c9dd2b-1ad2-4089-a157-c358c0422884"),
                            Contents = "Hello everyone! I hope you're doing well. I'm thrilled to announce the launch of our new alumni mentorship program.This initiative aims to connect recent graduates with seasoned professionals.It's a fantastic opportunity to share your knowledge, give back to our community, and guide the next generation. I look forward to seeing many of you participate!",
                            CreatedOn = new DateTime(2024, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastEdited = new DateTime(2024, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Test",
                            UserId = new Guid("7388ce0f-df30-4686-9e49-46daac4e0292")
                        });
                });

            modelBuilder.Entity("Alumni.Data.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastEdited")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8d7ed0e0-1804-4283-aa5b-802033b2c918"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b3a3a991-cd70-4f9f-882e-19d6ca310830",
                            CreatedOn = new DateTime(2024, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailConfirmed = false,
                            IsDeleted = false,
                            LastEdited = new DateTime(2024, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Vasko Bilkata"
                        },
                        new
                        {
                            Id = new Guid("30913bf8-4000-4809-801e-764de3136c0e"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9cc570fe-dc9a-4fc9-b6f2-766101ec0946",
                            CreatedOn = new DateTime(2024, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailConfirmed = false,
                            IsDeleted = true,
                            LastEdited = new DateTime(2024, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Michael Caine"
                        },
                        new
                        {
                            Id = new Guid("7388ce0f-df30-4686-9e49-46daac4e0292"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "496c63cb-858f-4fac-8964-b705fd3357f5",
                            CreatedOn = new DateTime(2024, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailConfirmed = false,
                            IsDeleted = false,
                            LastEdited = new DateTime(2024, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Prince Ferdinand"
                        },
                        new
                        {
                            Id = new Guid("b6a98fd4-b8db-4566-ad8c-d7c49f3bd2db"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2756ccca-fd9e-465c-9f3b-82e2f705efc6",
                            CreatedOn = new DateTime(2024, 7, 2, 5, 4, 7, 294, DateTimeKind.Local).AddTicks(759),
                            EmailConfirmed = false,
                            IsDeleted = false,
                            LastEdited = new DateTime(2024, 7, 9, 5, 4, 7, 294, DateTimeKind.Local).AddTicks(802),
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Burxh califchar"
                        },
                        new
                        {
                            Id = new Guid("6609e8af-abbe-4472-a1ff-ab5fdfb92f80"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cdb37f1a-268d-45b3-a4f2-ba3d88385596",
                            CreatedOn = new DateTime(2024, 7, 15, 5, 4, 7, 294, DateTimeKind.Local).AddTicks(811),
                            EmailConfirmed = false,
                            IsDeleted = true,
                            LastEdited = new DateTime(2024, 7, 16, 5, 4, 7, 294, DateTimeKind.Local).AddTicks(812),
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "gazelle trueman"
                        });
                });

            modelBuilder.Entity("Alumni.Data.Models.UserEvent", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "EventId");

                    b.HasIndex("EventId");

                    b.ToTable("UsersEvents");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Alumni.Data.Models.CharityDonationUser", b =>
                {
                    b.HasOne("Alumni.Data.Models.CharityDonation", "CharityDonation")
                        .WithMany("Donators")
                        .HasForeignKey("CharityDonationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alumni.Data.Models.User", "User")
                        .WithMany("CharityDonationsContributed")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharityDonation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Alumni.Data.Models.Comment", b =>
                {
                    b.HasOne("Alumni.Data.Models.News", null)
                        .WithMany("Comments")
                        .HasForeignKey("NewsId");

                    b.HasOne("Alumni.Data.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Alumni.Data.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Alumni.Data.Models.Post", b =>
                {
                    b.HasOne("Alumni.Data.Models.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Alumni.Data.Models.UserEvent", b =>
                {
                    b.HasOne("Alumni.Data.Models.Event", "Event")
                        .WithMany("EventUsers")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alumni.Data.Models.User", "User")
                        .WithMany("UserEvents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Alumni.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Alumni.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alumni.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Alumni.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Alumni.Data.Models.CharityDonation", b =>
                {
                    b.Navigation("Donators");
                });

            modelBuilder.Entity("Alumni.Data.Models.Event", b =>
                {
                    b.Navigation("EventUsers");
                });

            modelBuilder.Entity("Alumni.Data.Models.News", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Alumni.Data.Models.Post", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Alumni.Data.Models.User", b =>
                {
                    b.Navigation("CharityDonationsContributed");

                    b.Navigation("Comments");

                    b.Navigation("Posts");

                    b.Navigation("UserEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
